name: Szelvenykiraly Cron

on:
  # Kézzel is futtatható marad
  workflow_dispatch:

  # IDŐZÍTÉS – UTC-ben!
  schedule:
    # 07:00 UTC = 08:00 magyar idő (tél)
    - cron: "0 7 * * *"
    # 13:00 UTC = 14:00 magyar idő
    - cron: "0 13 * * *"
    # 18:00 UTC = 19:00 magyar idő
    - cron: "0 18 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Force httpx version (fix proxies error)
        run: |
          pip install "httpx<0.28"

      - name: Run tippmix bot
        run: |
          python -m bot.main
